# Plots

In [1]:
import datetime
import os

import matplotlib.lines as mlines
import matplotlib.patches as mpatches
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns

In [2]:
sns.set_theme(style="whitegrid", palette="deep")
task_palette = sns.color_palette("deep")
plt.rcParams["text.usetex"] = True
plt.rcParams.update({"figure.titlesize": "small"})
plt.rcParams.update({"axes.titlesize": "small"})
plt.rcParams.update({"axes.labelsize": "small"})
plt.rcParams.update({"ytick.labelsize": "small"})
plt.rcParams.update({"xtick.labelsize": "small"})
plt.rcParams.update({"legend.fontsize": "small"})

## Input data

In [3]:
from pathlib import Path

# Load baseline results from a single CSV file or from every CSV under a directory.
# When multiple files are loaded, later files can overwrite use cases already present.
path = Path("./results/0818/quarter")

## Schedulability Test

In [4]:
if path.is_dir():
    csv_paths = sorted(path.glob("*.csv"))
else:
    csv_paths = [path]

exclude_files = []
csv_paths = [p for p in csv_paths if p.name not in exclude_files]

if not csv_paths:
    raise FileNotFoundError(f"No CSV files found at {path}")

# Start from the first file, then merge the remaining ones one by one.
df_sch = pd.read_csv(csv_paths[0], sep=";")
for patch_path in csv_paths[1:]:
    df_patch = pd.read_csv(patch_path, sep=";")
    new_use_cases = set(df_patch["use_case"].unique())
    overwritten_use_cases = set(df_sch["use_case"].unique()).intersection(new_use_cases)
    if overwritten_use_cases:
        print(f"Overwriting use cases: {overwritten_use_cases}")
        df_sch = df_sch[~df_sch["use_case"].isin(overwritten_use_cases)]
    df_sch = pd.concat([df_sch, df_patch], ignore_index=True)

df_sch

,safe_oracles,quarter_clairvoyance,use_case,unsafe_oracles,scheduler,search_algorithms,taskset_file,taskset_position,U,Uv,...,probability_of_HI,min_period,max_period,timeout,is_safe_0,automaton_depth_0,visited_count_0,duration_ns_0,is_safe,duration_ns
0,[],False,"EDFVD (ACBFS, NC)",['hi-over-demand'],edfvd,['acbfs'],outputs/20260815_221032-schedulability-quarter...,6,0.5,0.495687,...,0.5,5.0,30.0,False,True,18,18356,79612714,True,79612714
1,[],False,"EDFVD (ACBFS, NC)",['hi-over-demand'],edfvd,['acbfs'],outputs/20260815_221032-schedulability-quarter...,5,0.5,0.498175,...,0.5,5.0,30.0,False,True,12,2648,16980006,True,16980006
2,[],False,"EDFVD (ACBFS, NC)",['hi-over-demand'],edfvd,['acbfs'],outputs/20260815_221032-schedulability-quarter...,10,0.5,0.495079,...,0.5,5.0,30.0,False,True,18,3715,28024256,True,28024256
3,[],False,"EDFVD (ACBFS, NC)",['hi-over-demand'],edfvd,['acbfs'],outputs/20260815_221032-schedulability-quarter...,16,0.5,0.504417,...,0.5,5.0,30.0,False,True,8,4991,18983977,True,18983977
4,[],False,"EDFVD (ACBFS, NC)",['hi-over-demand'],edfvd,['acbfs'],outputs/20260815_221032-schedulability-quarter...,7,0.5,0.500214,...,0.5,5.0,30.0,False,True,15,2068,12241731,True,12241731
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32995,[],True,"EDFVDSD (ACBFS, QC)",['hi-over-demand'],edfvdsd,['acbfs'],outputs/20260815_221032-schedulability-quarter...,10968,1.0,0.999635,...,0.5,5.0,30.0,False,True,1404,8865610,153874029667,True,153874029667
32996,[],True,"EDFVDSD (ACBFS, QC)",['hi-over-demand'],edfvdsd,['acbfs'],outputs/20260815_221032-schedulability-quarter...,10704,1.0,0.997901,...,0.5,5.0,30.0,False,True,1016,31317113,768564370710,True,768564370710
32997,[],True,"EDFVDSD (ACBFS, QC)",['hi-over-demand'],edfvdsd,['acbfs'],outputs/20260815_221032-schedulability-quarter...,10994,1.0,0.995795,...,0.5,5.0,30.0,False,True,699,15857822,236445676095,True,236445676095
32998,[],True,"EDFVDSD (ACBFS, QC)",['hi-over-demand'],edfvdsd,['acbfs'],outputs/20260815_221032-schedulability-quarter...,10931,1.0,0.996101,...,0.5,5.0,30.0,False,True,6479,20425436,404958297090,True,404958297090
32999,[],True,"EDFVDSD (ACBFS, QC)",['hi-over-demand'],edfvdsd,['acbfs'],outputs/20260815_221032-schedulability-quarter...,10961,1.0,0.997263,...,0.5,5.0,30.0,False,True,8874,46828953,693873123473,True,693873123473

In [5]:
def as_nullable_boolean(series, column_name):
    if pd.api.types.is_bool_dtype(series.dtype):
        return series.astype("boolean")
    normalized = series.replace({True: True, False: False, 1: True, 0: False,
                                 "True": True, "False": False, "true": True,
                                 "false": False, "1": True, "0": False})
    invalid = normalized.notna() & ~normalized.isin([True, False])
    if invalid.any():
        raise ValueError(f"Unexpected values in {column_name}: {series.loc[invalid].drop_duplicates().tolist()}")
    return normalized.astype("boolean")

def aggregate_exact_schedulability(frame):
    exact = frame.loc[:, ["U", "use_case", "is_safe", "timeout"]].copy()
    exact["timeout"] = as_nullable_boolean(exact["timeout"], "timeout")
    if exact["timeout"].isna().any():
        raise ValueError("Exact-search rows must have a timeout value")
    exact["is_safe"] = as_nullable_boolean(exact["is_safe"], "is_safe")
    inconsistent = exact["is_safe"].isna() & ~exact["timeout"]
    if inconsistent.any():
        rows = exact.index[inconsistent].tolist()[:10]
        raise ValueError(f"Missing is_safe without timeout=True at rows {rows}")
    exact["safe_count"] = exact["is_safe"].fillna(False).astype("int64")
    exact["timeout_count"] = exact["timeout"].astype("int64")
    aggregated = (exact.groupby(["use_case", "U"], as_index=False)
        .agg(total=("is_safe", "size"), safe=("safe_count", "sum"),
             timed_out=("timeout_count", "sum")))
    aggregated["schedulability_ratio"] = aggregated["safe"] / aggregated["total"]
    aggregated["timeout_ratio"] = aggregated["timed_out"] / aggregated["total"]
    return aggregated

df_exact_agg = aggregate_exact_schedulability(df_sch)
df_exact_agg

,use_case,U,total,safe,timed_out,schedulability_ratio,timeout_ratio
0,"EDFVD (ACBFS, NC)",0.50,1000,1000,0,1.0,0.0
1,"EDFVD (ACBFS, NC)",0.55,1000,1000,0,1.0,0.0
2,"EDFVD (ACBFS, NC)",0.60,1000,999,0,0.999,0.0
3,"EDFVD (ACBFS, NC)",0.65,1000,1000,0,1.0,0.0
4,"EDFVD (ACBFS, NC)",0.70,1000,995,0,0.995,0.0
5,"EDFVD (ACBFS, NC)",0.75,1000,979,0,0.979,0.0
6,"EDFVD (ACBFS, NC)",0.80,1000,960,0,0.96,0.0
7,"EDFVD (ACBFS, NC)",0.85,1000,855,0,0.855,0.0
8,"EDFVD (ACBFS, NC)",0.90,1000,640,0,0.64,0.0
9,"EDFVD (ACBFS, NC)",0.95,1000,312,0,0.312,0.0
10,"EDFVD (ACBFS, NC)",1.00,1000,37,0,0.037,0.0
11,"EDFVD (ACBFS, QC)",0.50,1000,1000,0,1.0,0.0
12,"EDFVD (ACBFS, QC)",0.55,1000,1000,0,1.0,0.0
13,"EDFVD (ACBFS, QC)",0.60,1000,1000,0,1.0,0.0
14,"EDFVD (ACBFS, QC)",0.65,1000,1000,0,1.0,0.0
15,"EDFVD (ACBFS, QC)",0.70,1000,1000,0,1.0,0.0
16,"EDFVD (ACBFS, QC)",0.75,1000,1000,0,1.0,0.0
17,"EDFVD (ACBFS, QC)",0.80,1000,998,0,0.998,0.0
18,"EDFVD (ACBFS, QC)",0.85,1000,969,0,0.969,0.0
19,"EDFVD (ACBFS, QC)",0.90,1000,927,0,0.927,0.0
20,"EDFVD (ACBFS, QC)",0.95,1000,855,0,0.855,0.0
21,"EDFVD (ACBFS, QC)",1.00,1000,650,0,0.65,0.0
22,"EDFVDSD (ACBFS, QC)",0.50,1000,1000,0,1.0,0.0
23,"EDFVDSD (ACBFS, QC)",0.55,1000,1000,0,1.0,0.0
24,"EDFVDSD (ACBFS, QC)",0.60,1000,1000,0,1.0,0.0
25,"EDFVDSD (ACBFS, QC)",0.65,1000,1000,0,1.0,0.0
26,"EDFVDSD (ACBFS, QC)",0.70,1000,1000,0,1.0,0.0
27,"EDFVDSD (ACBFS, QC)",0.75,1000,1000,0,1.0,0.0
28,"EDFVDSD (ACBFS, QC)",0.80,1000,1000,0,1.0,0.0
29,"EDFVDSD (ACBFS, QC)",0.85,1000,1000,0,1.0,0.0
30,"EDFVDSD (ACBFS, QC)",0.90,1000,998,0,0.998,0.0
31,"EDFVDSD (ACBFS, QC)",0.95,1000,979,0,0.979,0.0
32,"EDFVDSD (ACBFS, QC)",1.00,1000,851,0,0.851,0.0

Taskset Parameters:
- safe_oracles: safe oracles applied to the search algorithm
- unsafe_oracles: unsafe oracles applied to the search algorithm
- use_case: name of the scheduler and chained search algorithms configuration
- taskset_position: position of the taskset in the original generation

Split the raw table into:
- df_edfvd_test: from EDFVD_test column of the raw table, rename the use_case into "EDF-VD (sufficient)"
- df_stages[i]: from stage i of search algorithm of the raw table.
    - stage: i
    - search_algorithm: from search_algorithms[i]
    - schedulable: from is_safe_{i}
    - automaton_depth: from automaton_depth_{i}
    - visited_count: from visited_count_{i}
    - duration_ns: from duration_ns_{i}
- df_combined: for the combined final result of the search algorithm combinations.

In [6]:
# EDF-VD test
df_edfvd_test = df_sch[["taskset_position", "EDFVD_test", "U"]]
df_edfvd_test = df_edfvd_test.rename(columns={"EDFVD_test": "EDF-VD (sufficient)"})
df_edfvd_test["EDF-VD (sufficient)"] = as_nullable_boolean(df_edfvd_test["EDF-VD (sufficient)"], "EDFVD_test")
df_edfvd_test = df_edfvd_test.melt(
    id_vars=["taskset_position", "U"], var_name="use_case", value_name="schedulable"
)
df_edfvd_test["stage"] = -1

df_edfvd_test

       taskset_position    U             use_case  schedulable  stage
0                     6  0.5  EDF-VD (sufficient)         True     -1
1                     5  0.5  EDF-VD (sufficient)         True     -1
2                    10  0.5  EDF-VD (sufficient)         True     -1
3                    16  0.5  EDF-VD (sufficient)         True     -1
4                     7  0.5  EDF-VD (sufficient)         True     -1
...                 ...  ...                  ...          ...    ...
32995             10968  1.0  EDF-VD (sufficient)        False     -1
32996             10704  1.0  EDF-VD (sufficient)        False     -1
32997             10994  1.0  EDF-VD (sufficient)        False     -1
32998             10931  1.0  EDF-VD (sufficient)        False     -1
32999             10961  1.0  EDF-VD (sufficient)        False     -1

[33000 rows x 5 columns]

In [7]:
# new EDF-VD test
df_edfvd_test_new = df_sch[["taskset_position", "EDFVD_test_new", "U"]]
df_edfvd_test_new = df_edfvd_test_new.rename(columns={"EDFVD_test_new": "EDF-VD (sufficient, new)"})
df_edfvd_test_new["EDF-VD (sufficient, new)"] = as_nullable_boolean(df_edfvd_test_new["EDF-VD (sufficient, new)"], "EDFVD_test_new")
df_edfvd_test_new = df_edfvd_test_new.melt(
    id_vars=["taskset_position", "U"], var_name="use_case", value_name="schedulable"
)
df_edfvd_test_new["stage"] = -1

df_edfvd_test_new

       taskset_position    U                  use_case  schedulable  stage
0                     6  0.5  EDF-VD (sufficient, new)         True     -1
1                     5  0.5  EDF-VD (sufficient, new)         True     -1
2                    10  0.5  EDF-VD (sufficient, new)         True     -1
3                    16  0.5  EDF-VD (sufficient, new)         True     -1
4                     7  0.5  EDF-VD (sufficient, new)         True     -1
...                 ...  ...                       ...          ...    ...
32995             10968  1.0  EDF-VD (sufficient, new)        False     -1
32996             10704  1.0  EDF-VD (sufficient, new)        False     -1
32997             10994  1.0  EDF-VD (sufficient, new)        False     -1
32998             10931  1.0  EDF-VD (sufficient, new)        False     -1
32999             10961  1.0  EDF-VD (sufficient, new)        False     -1

[33000 rows x 5 columns]

In [8]:
# EDF-VDSD test
df_edfvdsd_test = df_sch[["taskset_position", "EDFVDSD_test", "U"]]
df_edfvdsd_test = df_edfvdsd_test.rename(columns={"EDFVDSD_test": "EDF-VDSD (sufficient)"})
df_edfvdsd_test["EDF-VDSD (sufficient)"] = as_nullable_boolean(df_edfvdsd_test["EDF-VDSD (sufficient)"], "EDFVDSD_test")
df_edfvdsd_test = df_edfvdsd_test.melt(
    id_vars=["taskset_position", "U"], var_name="use_case", value_name="schedulable"
)
df_edfvdsd_test["stage"] = -1

df_edfvdsd_test

       taskset_position    U               use_case  schedulable  stage
0                     6  0.5  EDF-VDSD (sufficient)         True     -1
1                     5  0.5  EDF-VDSD (sufficient)         True     -1
2                    10  0.5  EDF-VDSD (sufficient)         True     -1
3                    16  0.5  EDF-VDSD (sufficient)         True     -1
4                     7  0.5  EDF-VDSD (sufficient)         True     -1
...                 ...  ...                    ...          ...    ...
32995             10968  1.0  EDF-VDSD (sufficient)        False     -1
32996             10704  1.0  EDF-VDSD (sufficient)        False     -1
32997             10994  1.0  EDF-VDSD (sufficient)        False     -1
32998             10931  1.0  EDF-VDSD (sufficient)        False     -1
32999             10961  1.0  EDF-VDSD (sufficient)        False     -1

[33000 rows x 5 columns]

In [9]:
# OPT Semi-clairvoyant test
df_opt_semi_test = df_sch[["taskset_position", "OPT_SEMI_test", "U"]]
df_opt_semi_test = df_opt_semi_test.rename(columns={"OPT_SEMI_test": "SEMI (optimal)"})
df_opt_semi_test["SEMI (optimal)"] = as_nullable_boolean(df_opt_semi_test["SEMI (optimal)"], "OPT_SEMI_test")
df_opt_semi_test = df_opt_semi_test.melt(
    id_vars=["taskset_position", "U"], var_name="use_case", value_name="schedulable"
)
df_opt_semi_test["stage"] = -1

df_opt_semi_test

       taskset_position    U        use_case  schedulable  stage
0                     6  0.5  SEMI (optimal)         True     -1
1                     5  0.5  SEMI (optimal)         True     -1
2                    10  0.5  SEMI (optimal)         True     -1
3                    16  0.5  SEMI (optimal)         True     -1
4                     7  0.5  SEMI (optimal)         True     -1
...                 ...  ...             ...          ...    ...
32995             10968  1.0  SEMI (optimal)         True     -1
32996             10704  1.0  SEMI (optimal)         True     -1
32997             10994  1.0  SEMI (optimal)         True     -1
32998             10931  1.0  SEMI (optimal)         True     -1
32999             10961  1.0  SEMI (optimal)         True     -1

[33000 rows x 5 columns]

In [10]:
df_total = df_exact_agg.rename(columns={"schedulability_ratio": "schedulable"})
df_total = df_total.replace(r"ACBFS, ", "", regex=True)
df_total["stage"] = -1

df_total

,use_case,U,total,safe,timed_out,schedulable,timeout_ratio,stage
0,EDFVD (NC),0.50,1000,1000,0,1.0,0.0,-1
1,EDFVD (NC),0.55,1000,1000,0,1.0,0.0,-1
2,EDFVD (NC),0.60,1000,999,0,0.999,0.0,-1
3,EDFVD (NC),0.65,1000,1000,0,1.0,0.0,-1
4,EDFVD (NC),0.70,1000,995,0,0.995,0.0,-1
5,EDFVD (NC),0.75,1000,979,0,0.979,0.0,-1
6,EDFVD (NC),0.80,1000,960,0,0.96,0.0,-1
7,EDFVD (NC),0.85,1000,855,0,0.855,0.0,-1
8,EDFVD (NC),0.90,1000,640,0,0.64,0.0,-1
9,EDFVD (NC),0.95,1000,312,0,0.312,0.0,-1
10,EDFVD (NC),1.00,1000,37,0,0.037,0.0,-1
11,EDFVD (QC),0.50,1000,1000,0,1.0,0.0,-1
12,EDFVD (QC),0.55,1000,1000,0,1.0,0.0,-1
13,EDFVD (QC),0.60,1000,1000,0,1.0,0.0,-1
14,EDFVD (QC),0.65,1000,1000,0,1.0,0.0,-1
15,EDFVD (QC),0.70,1000,1000,0,1.0,0.0,-1
16,EDFVD (QC),0.75,1000,1000,0,1.0,0.0,-1
17,EDFVD (QC),0.80,1000,998,0,0.998,0.0,-1
18,EDFVD (QC),0.85,1000,969,0,0.969,0.0,-1
19,EDFVD (QC),0.90,1000,927,0,0.927,0.0,-1
20,EDFVD (QC),0.95,1000,855,0,0.855,0.0,-1
21,EDFVD (QC),1.00,1000,650,0,0.65,0.0,-1
22,EDFVDSD (QC),0.50,1000,1000,0,1.0,0.0,-1
23,EDFVDSD (QC),0.55,1000,1000,0,1.0,0.0,-1
24,EDFVDSD (QC),0.60,1000,1000,0,1.0,0.0,-1
25,EDFVDSD (QC),0.65,1000,1000,0,1.0,0.0,-1
26,EDFVDSD (QC),0.70,1000,1000,0,1.0,0.0,-1
27,EDFVDSD (QC),0.75,1000,1000,0,1.0,0.0,-1
28,EDFVDSD (QC),0.80,1000,1000,0,1.0,0.0,-1
29,EDFVDSD (QC),0.85,1000,1000,0,1.0,0.0,-1
30,EDFVDSD (QC),0.90,1000,998,0,0.998,0.0,-1
31,EDFVDSD (QC),0.95,1000,979,0,0.979,0.0,-1
32,EDFVDSD (QC),1.00,1000,851,0,0.851,0.0,-1

In [11]:
df_bounds = pd.concat([df_edfvd_test, df_edfvd_test_new, df_edfvdsd_test, df_opt_semi_test], ignore_index=True)

df_bounds

        taskset_position    U             use_case  schedulable  stage
0                      6  0.5  EDF-VD (sufficient)         True     -1
1                      5  0.5  EDF-VD (sufficient)         True     -1
2                     10  0.5  EDF-VD (sufficient)         True     -1
3                     16  0.5  EDF-VD (sufficient)         True     -1
4                      7  0.5  EDF-VD (sufficient)         True     -1
...                  ...  ...                  ...          ...    ...
131995             10968  1.0       SEMI (optimal)         True     -1
131996             10704  1.0       SEMI (optimal)         True     -1
131997             10994  1.0       SEMI (optimal)         True     -1
131998             10931  1.0       SEMI (optimal)         True     -1
131999             10961  1.0       SEMI (optimal)         True     -1

[132000 rows x 5 columns]

### Plots the schedulability

In [12]:
fig_size = (5, 5)

In [13]:
f, ax = plt.subplots(figsize=fig_size)

bound_cols = df_bounds["use_case"].unique()
result_cols = df_total["use_case"].unique()
col_order = list(bound_cols) + list(result_cols)
use_case_colors = dict(zip(col_order, sns.color_palette("deep", n_colors=len(col_order))))

# Plot bounds with solid lines
sns.lineplot(
    data=df_bounds,
    x="U",
    y="schedulable",
    hue="use_case",
    ax=ax,
    markers=True,
    errorbar=None,
    style="use_case",
    ms=9,
    hue_order=col_order,
    style_order=col_order,
    dashes=False
)

# Plot results with dotted lines
sns.lineplot(
    data=df_total,
    x="U",
    y="schedulable",
    hue="use_case",
    ax=ax,
    markers=True,
    errorbar=None,
    style="use_case",
    ms=9,
    hue_order=col_order,
    style_order=col_order,
    palette=use_case_colors,
    dashes=True,
    legend=False
)

ax.set_ylabel("Schedulability ratio (lower bound)")
ax.set_ylim(0, 1.02)
ax.set_xlabel("Average utilisation ($U^*$)")

ax.set_title(
    r"$P_{\mathsf{HI}} = 0.5, T^{\mathsf{min}} = 5, T^{\mathsf{max}} = 30, n=5$",
)

handles, labels = ax.get_legend_handles_labels()

f.tight_layout()

/home/ochremarsh/Documents/real-time-systems/mixed-criticality-graph-xp/.venv-host/lib/python3.12/site-packages/seaborn/relational.py:293: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  sub_data = grouped.apply(agg, other).reset_index()
/home/ochremarsh/Documents/real-time-systems/mixed-criticality-graph-xp/.venv-host/lib/python3.12/site-packages/seaborn/relational.py:293: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  sub_data = grouped.apply(agg, other).reset_index()
/home/ochremarsh/Documents/real-time-systems/mixed-criticality-graph-xp/.venv-host/lib/python3.12/site-packages/seaborn/relational.py:293: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  sub_data = grouped.apply(agg, other).reset_index()
/home/ochremarsh/Documents/real-time-systems/mixed-criticality-graph-xp/.venv-host/lib/python3.12/site-packages/seaborn/relational.py:293: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  sub_data = grouped.apply(agg, other).reset_index()

In [15]:
date = datetime.datetime.now().strftime("%Y%m%d")
os.makedirs(f"./figs/{date}", exist_ok=True)
f.savefig(
    f"./figs/{date}/{datetime.datetime.now().strftime('%Y%m%d_%H%M%S')}_scheduling.eps",
    bbox_inches="tight",
)
f.savefig(
    f"./figs/{date}/{datetime.datetime.now().strftime('%Y%m%d_%H%M%S')}_scheduling.png",
    bbox_inches="tight",
)

The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.

### Plots the time taken vs average utilization for each algorithm

In [ ]:
f, ax = plt.subplots(figsize=fig_size)

df_time = (
    df_sch.loc[:, ["U", "duration_ns", "use_case"]]
    .dropna(how="any")
    .assign(duration_s=lambda d: d["duration_ns"] / 1e9)
    .sort_values(["use_case", "U"])
)

sns.lineplot(
    data=df_time,
    x="U",
    y="duration_s",
    hue="use_case",
    style="use_case",
    marker="o",
    ax=ax,
)

ax.set_ylabel("Time taken (s)")
ax.set_xlabel("Average utilisation ($U^*$)")

ax.set_title(
    r"$P_{\mathsf{HI}} = 0.5, n=5$",
)

sns.move_legend(
    ax,
    loc="upper left",
    framealpha=1,
    title="",
)

In [ ]:
date = datetime.datetime.now().strftime("%Y%m%d")
os.makedirs(f"./figs/{date}", exist_ok=True)
f.savefig(
    f"./figs/{date}/{datetime.datetime.now().strftime('%Y%m%d_%H%M%S')}_time_uavg.eps",
    bbox_inches="tight",
)
f.savefig(
    f"./figs/{date}/{datetime.datetime.now().strftime('%Y%m%d_%H%M%S')}_time_uavg.png",
    bbox_inches="tight",
)

### Plot speed up compared to basedline ACBFS

In [ ]:
baseline_use_case = "EDF-VD (AC)"
df_baseline = df_sch[df_sch["use_case"] == baseline_use_case]

use_cases = df_sch["use_case"].unique()
test_cases = use_cases[use_cases != baseline_use_case]
test_cases

In [ ]:
def get_speedup(use_case):
    df_baseline = df_sch[df_sch["use_case"] == baseline_use_case]
    df_test = df_sch[df_sch["use_case"] == use_case]
    df_speedup = df_test.copy()
    df_speedup["speedup"] = df_baseline["duration_ns"] / df_test["duration_ns"]
    return df_speedup

In [ ]:
df_use_cases = {use_case: df_sch[df_sch["use_case"] == use_case].loc[:, ["U", "duration_ns", "is_safe", "use_case"]].reset_index(drop=True) for use_case in use_cases}
df_use_cases[baseline_use_case]

In [ ]:
rows = []

base_df = df_use_cases[baseline_use_case].reset_index(drop=True)

for test_case in test_cases:
    test_df = df_use_cases[test_case].reset_index(drop=True)

    tmp = test_df.copy()

    tmp["speedup"] = (
        base_df["duration_ns"] / test_df["duration_ns"]
    )

    tmp["comparison_case"] = test_case

    rows.append(
        tmp.loc[:, ["U", "speedup", "comparison_case", "is_safe"]]
    )

df_speedup_all = pd.concat(rows, ignore_index=True)

f, ax = plt.subplots(figsize=fig_size)

sns.boxplot(
    data=df_speedup_all,
    x="U",
    y="speedup",
    hue="comparison_case",
    dodge=True,
    ax=ax,
)

ax.set_yscale("log")

ax.axhline(
    1.0,
    linestyle="--",
    linewidth=1,
)

ax.set_ylabel("Speedup vs baseline")
ax.set_xlabel(r"Average utilisation ($U^*$)")

ax.set_title(
    f"Speedup against {baseline_use_case}"
)

sns.move_legend(
    ax,
    loc="upper left",
    title="Test case",
    framealpha=1,
)

In [ ]:
plt.show()
date = datetime.datetime.now().strftime('%Y%m%d')
os.makedirs(f"./figs/{date}", exist_ok=True)
f.savefig(
    f"./figs/{date}/{datetime.datetime.now().strftime('%Y%m%d_%H%M%S')}_speedup.eps",
    bbox_inches="tight",
)
f.savefig(
    f"./figs/{date}/{datetime.datetime.now().strftime('%Y%m%d_%H%M%S')}_speedup.png",
    bbox_inches="tight",
)
f.savefig(
    f"./figs/speedup.eps",
    bbox_inches="tight",
)

### By stage

In [ ]:
# Stages
n_stages = df_sch["search_algorithms"].iloc[0].count(",") + 1
df_stages = []

for i in range(n_stages):
    df_stage = df_sch[["taskset_position", "use_case", "U", f"is_safe_{i}", f"automaton_depth_{i}", f"visited_count_{i}", f"duration_ns_{i}"]]
    df_stage = df_stage.rename(columns={f"is_safe_{i}": "schedulable", f"automaton_depth_{i}": "automaton_depth", f"visited_count_{i}": "visited_count", f"duration_ns_{i}": "duration_ns"})
    df_stage["schedulable"] = as_nullable_boolean(df_stage["schedulable"], f"is_safe_{i}")
    df_stage["stage"] = i
    df_stage["search_algorithm"] = df_sch["search_algorithms"].apply(lambda x: x.strip("[]").split(", ")[i].strip("'"))
    df_stages.append(df_stage)

df_stages[-1]

Plot schedulability by stage for a specific algorithm

In [ ]:
def plot_schedulability_by_stage(use_case):
    f, ax = plt.subplots(figsize=fig_size)

    df_scheds = []

    df_sched = df_sched_comb.loc[df_sched_comb["use_case"] == use_case]
    df_sched["search_algorithm"] = "Overall"
    df_scheds.append(df_sched)

    for i in range(n_stages):
        df_scheds.append(
            df_stages[i].loc[:, ["U", "schedulable", "use_case", "search_algorithm", "stage"]][df_stages[i]["use_case"] == use_case]
        )

    df_combined = pd.concat(df_scheds, ignore_index=True)
    search_algorithms = df_combined["search_algorithm"].unique()

    sns.lineplot(
        data=df_combined,
        x="U",
        y="schedulable",
        ax=ax,
        markers=True,
        errorbar=None,
        ms=9,
        hue="search_algorithm",
        hue_order=search_algorithms,
        style="search_algorithm",
        style_order=search_algorithms,
    )

    ax.set_ylabel("Schedulability ratio")
    ax.set_xlabel("Average utilisation ($U^*$)")
    ax.set_title(f'Schedulability by stages - {use_case}')

    return f

In [ ]:
use_cases = df_sch["use_case"].unique()
use_cases

In [ ]:
for use_case in use_cases:
    f = plot_schedulability_by_stage(use_case)
    date = datetime.datetime.now().strftime('%Y%m%d')
    os.makedirs(f"./figs/{date}", exist_ok=True)
    f.savefig(
        f"./figs/{date}/{datetime.datetime.now().strftime('%Y%m%d_%H%M%S')}_schedulability_by_stage_{use_case.replace(' ', '_')}.eps",
        bbox_inches="tight",
    )
    f.savefig(
        f"./figs/{date}/{datetime.datetime.now().strftime('%Y%m%d_%H%M%S')}_schedulability_by_stage_{use_case.replace(' ', '_')}.png",
        bbox_inches="tight",
    )
    f.savefig(
        f"./figs/schedulability_by_stage_{use_case.replace(' ', '_')}.eps",
        bbox_inches="tight",
    )

Plots the time taken by stage for a specific algorithm

In [ ]:
rows = []

for test_case in test_cases:
    test_df = df_use_cases[test_case].reset_index(drop=True)

    tmp = test_df.copy()

    tmp["speedup"] = (
        base_df["duration_ns"] / test_df["duration_ns"]
    )

    tmp["comparison_case"] = test_case

    rows.append(
        tmp.loc[:, ["U", "speedup", "comparison_case", "is_safe"]]
    )

df_speedup_all = pd.concat(rows, ignore_index=True)

# Compute statistics
df_stats = (
    df_speedup_all
    .groupby(["comparison_case", "U"])["speedup"]
    .agg(
        geometric_mean=lambda x: np.exp(np.mean(np.log(x))),
        max_speedup="max",
    )
    .reset_index()
)
df_stats

In [ ]:
f, ax = plt.subplots(figsize=fig_size)

sns.lineplot(
    data=df_stats,
    x="U",
    y="geometric_mean",
    hue="comparison_case",
    marker="o",
    ax=ax,
)

ax.set_ylabel("Geometric Mean Speedup")
ax.set_xlabel("U")

plt.show()

In [ ]:
def plot_time_by_stage(use_case):
    f, ax = plt.subplots(figsize=fig_size)

    df_times = []
    for i in range(n_stages):
        df_stage = df_stages[i].loc[:, ["U", "duration_ns", "use_case", "search_algorithm", "stage"]]
        df_stage = df_stage[df_stage["use_case"] == use_case].dropna(how="any")
        df_times.append(
            df_stage.assign(
                duration_s=lambda d: d["duration_ns"] / 1e9,
            )
        )

    df_combined = pd.concat(df_times, ignore_index=True)
    df_combined = df_combined[df_combined["stage"].notna() & (df_combined["stage"] >= 0)]
    df_combined["stage"] = df_combined["stage"].astype(int)

    df_plot = (
        df_combined.groupby(["U", "stage"], as_index=False)["duration_s"]
        .mean()
        .sort_values(["U", "stage"])
    )

    stage_order = sorted(df_plot["stage"].unique())
    pivot = (
        df_plot.pivot(index="U", columns="stage", values="duration_s")
        .reindex(columns=stage_order)
        .fillna(0)
        .sort_index()
    )

    stage_to_search_alg = df_combined.set_index("stage")["search_algorithm"].to_dict()

    x = pivot.index.to_numpy(dtype=float)
    bottom = np.zeros(len(pivot), dtype=float)
    stage_colors = sns.color_palette("deep", n_colors=len(stage_order))

    for stage, color in zip(stage_order, stage_colors):
        values = pivot[stage].to_numpy(dtype=float)
        ax.bar(
            x,
            values,
            bottom=bottom,
            width=0.04,
            color=color,
            edgecolor="white",
            linewidth=0.4,
            label=f"Stage {stage + 1}: {stage_to_search_alg.get(stage, 'Unknown')}",
        )
        bottom += values

    ax.set_ylabel("Time taken (s)")
    ax.set_xlabel("Average utilisation ($U^*$)")
    ax.set_title(f"Time by stages - {use_case}")
    ax.legend(title="Stage", framealpha=1)

    return f

In [ ]:
f = plot_time_by_stage(use_cases[1])
f.show()

In [ ]:
for use_case in use_cases:
    f = plot_time_by_stage(use_case)
    date = datetime.datetime.now().strftime('%Y%m%d')
    os.makedirs(f"./figs/{date}", exist_ok=True)
    f.savefig(
        f"./figs/{date}/{datetime.datetime.now().strftime('%Y%m%d_%H%M%S')}_time_by_stage_{use_case.replace(' ', '_')}.eps",
        bbox_inches="tight",
    )
    f.savefig(
        f"./figs/{date}/{datetime.datetime.now().strftime('%Y%m%d_%H%M%S')}_time_by_stage_{use_case.replace(' ', '_')}.png",
        bbox_inches="tight",
    )
    f.savefig(
        f"./figs/time_by_stage_{use_case.replace(' ', '_')}.eps",
        bbox_inches="tight",
    )

## Antichain Test

In [ ]:
path = "./results/results-mcs_scale_bfs-2026-04-15_20-29-06.csv"
df = pd.read_csv(path, sep=";")
df

In [ ]:
df["duration_s"] = df["duration_ns"] / 1e9
df["search_type"] = df["use_idlesim"].apply(lambda x: "ACBFS" if x else "BFS")
df = df.dropna(how="any")

In [ ]:
s = df.shape[0] * [True]
df_plot = df.loc[s]
df_piv = df_plot.copy().pivot(
    index="taskset_position",
    columns="search_type",
    values=["duration_s", "visited_count", "max_period", "nbt"],
)
df_piv.columns = list(map(lambda x: "_".join(x), df_piv.columns))
df_piv = df_piv.dropna(how="any")

In [ ]:
df_piv["Number of tasks"] = df_piv["nbt_BFS"].astype(int)
df_piv["Period max"] = df_piv["max_period_ACBFS"].astype(int)
df_piv["n"] = df_piv["nbt_BFS"].astype(int)
df_piv["T max"] = df_piv["max_period_ACBFS"].astype(int)

In [ ]:
f, ax = plt.subplots(figsize=(6, 3))

sns.scatterplot(
    data=df_piv,
    x="duration_s_BFS",
    y="duration_s_ACBFS",
    style="T max",
    hue="n",
    ax=ax,
    palette=task_palette,
)
ax.set(xscale="log", yscale="log")
# ax.axis("equal")

lims = [
    10**-5.1,
    np.max([ax.get_xlim(), ax.get_ylim()]),  # max of both axes
]

# now plot both limits against eachother
ax.plot(lims, lims, "k--", alpha=0.75, zorder=1)

ax.set(xlim=lims, ylim=lims)

ax.set_xlabel("BFS")
ax.set_ylabel("ACBFS")
ax.set_title("Execution time (s)")

# sns.move_legend(ax, "upper left", bbox_to_anchor=(1, 1.1))

f.suptitle(r"$P_{\mathsf{HI}} = 0.5, T^{\mathsf{min}} = 5, U^{*} = 0.5$", y=1.02)

h, l = ax.get_legend_handles_labels()
ax.legend_.remove()
leg = [
    "$n$",
    "2",
    "3",
    "4",
    "5",
    "6",
    "$T^{\mathsf{max}}$",
    "10",
    "15",
    "20",
    "25",
    "30",
]
f.legend(h, leg, ncol=2, loc="upper left", bbox_to_anchor=(0.15, 0.85), framealpha=1)


x = np.log10(df_piv.sort_values(by="duration_s_BFS")["duration_s_BFS"])
y = np.log10(df_piv.sort_values(by="duration_s_BFS")["duration_s_ACBFS"])
m, b = np.polyfit(x, y, 1)
x_reg = np.linspace(lims, 100)
x_reg = np.log10(x_reg)
plt.plot(10**x_reg, 10 ** (m * x_reg + b), color="k", ls=":")

In [ ]:
f.savefig(
    f"./figs/{datetime.datetime.now().strftime('%Y%m%d_%H%M%S')}_bfs_acbfs.eps",
    bbox_inches="tight",
)
f.savefig(
    "./figs/bfs_acbfs.eps",
    bbox_inches="tight",
)

## Scalability Test

In [ ]:
path = "./results/0817/results-mcs_statespace_edfvd_nc-2026-08-17_18-42-38.csv"

df_sp = pd.read_csv(path, sep=";")
df_sp

In [ ]:
df_sp["taskset_file"].value_counts()

In [ ]:
df_sp.groupby("taskset_file")["taskset_position"].max()

In [ ]:
df_sp["duration_s"] = df_sp["duration_ns"] / 1e9

In [ ]:
df_sp["timeout_int"] = df_sp["timeout"].astype(int)
df_sp.groupby(["nbt"])["timeout_int"].agg(["count", "sum"])

In [ ]:
df_sp.groupby("nbt")["duration_s"].describe()

In [ ]:
# f, axs = plt.subplots(2, 1, figsize=(3.5*52/98*2, 3.5), gridspec_kw={"hspace": 0.25})
f, axs = plt.subplots(
    2, 1, figsize=(3.2 / 1.05, 3.2), gridspec_kw={"hspace": 0.25}, sharey=True
)


ax1 = axs[0]
ax2 = ax1.twinx()

# s = df_sp["taskset_file"].str.contains("task")
# dimension = "nbt"

s = df_sp["taskset_file"].str.contains("period")
dimension = "max_period"

# s &= df_sp["use_case"] == "ACBFS, no oracle"


n_xp = 50

x_val = np.sort(df_sp.loc[s, dimension].unique())
x_val = list(map(int, x_val))
y_val_line = []
y_val_bar = []
for x in x_val:
    y_line = df_sp.loc[s & (df_sp[dimension] == x), "duration_s"].mean()
    y_val_line.append(y_line)

    y_bar = df_sp.loc[s & (df_sp[dimension] == x), "timeout_int"].sum()
    y_bar += n_xp - df_sp.loc[s & (df_sp[dimension] == x), "timeout_int"].count()
    y_val_bar.append(y_bar)

sns.lineplot(
    x=x_val,
    y=y_val_line,
    ax=ax1,
    marker="o",
    ms=9,
    estimator="median",
)
ax1.set(yscale="log")

ax2.bar(
    x=x_val,
    height=y_val_bar,
    color="w",
    edgecolor=task_palette[1],
    hatch="//",
    alpha=1,
    width=(x_val[1] - x_val[0]) * 0.8,
)

ax2.grid(False)
ax2.set_ylim(0, n_xp)


ax1.set_xlabel("Number of tasks ($n$), $T^{\mathsf{max}} = 30$")
ax1.set_ylabel("Execution time (s)")
ax2.set_ylabel("Timeouts")
ax1.minorticks_off()

ax1.xaxis.tick_top()
ax1.xaxis.set_label_position("top")
ax1.xaxis.set_ticks_position("none")
ax1.yaxis.set_ticks_position("none")
ax2.yaxis.set_ticks_position("none")
ax1.tick_params(axis="x", which="major", pad=0)


ax1 = axs[1]
ax2 = ax1.twinx()

s = df_sp["taskset_file"].str.contains("task")
dimension = "nbt"

# s = df_sp["taskset_file"].str.contains("period")
# dimension = "max_period"

# s &= df_sp["use_case"] == "ACBFS, no oracle"


x_val = np.sort(df_sp.loc[s, dimension].unique())
x_val = list(map(int, x_val))
y_val_line = []
y_val_bar = []
for x in x_val:
    y_line = df_sp.loc[s & (df_sp[dimension] == x), "duration_s"].mean()
    y_val_line.append(y_line)

    y_bar = df_sp.loc[s & (df_sp[dimension] == x), "timeout_int"].sum()
    y_bar += n_xp - df_sp.loc[s & (df_sp[dimension] == x), "timeout_int"].count()
    y_val_bar.append(y_bar)

sns.lineplot(
    x=x_val,
    y=y_val_line,
    ax=ax1,
    marker="o",
    ms=9,
    estimator="median",
)
ax1.set(yscale="log")

ax2.bar(
    x=x_val,
    height=y_val_bar,
    color="w",
    edgecolor=task_palette[1],
    hatch="//",
    alpha=1,
    width=(x_val[1] - x_val[0]) * 0.8,
)

ax2.grid(False)
ax2.set_ylim(0, n_xp)


ax1.set_xlabel("Period max ($T^{\mathsf{max}}$), $n = 5$")
ax1.set_ylabel("Execution time (s)", labelpad=10)
ax2.set_ylabel("Timeouts")
ax1.minorticks_off()
ax1.yaxis.set_ticks_position("none")
ax2.yaxis.set_ticks_position("none")

f.suptitle(
    r"$P_{\mathsf{HI}} = 0.5, T^{\mathsf{min}} = 5, U^{*} = 0.5$",
    # x=0.55,
    # y=0.96,
    y=1.05,
)

blue_line = mlines.Line2D(
    [],
    [],
    color=task_palette[0],
    marker="o",
    linestyle="-",
    markeredgecolor="w",
    label="Execution time (s)",
    ms=9,
)

orange_box = mpatches.Patch(
    hatch="//", label="Timeouts", edgecolor=task_palette[1], facecolor="white"
)

new_handles = [blue_line, orange_box]


ax1.legend(
    handles=new_handles,
    loc="upper center",
    ncol=2,
    framealpha=0,
    columnspacing=0.8,
    bbox_to_anchor=(0.5, 1.28),
)

ax1.get_ylim()


f.tight_layout()

In [ ]:
date = datetime.datetime.now().strftime("%Y%m%d")
os.makedirs(f"./figs/{date}", exist_ok=True)
f.savefig(
    f"./figs/{date}/{datetime.datetime.now().strftime('%Y%m%d_%H%M%S')}_tmax_ntask.eps",
    bbox_inches="tight",
)
f.savefig(
    f"./figs/{date}/{datetime.datetime.now().strftime('%Y%m%d_%H%M%S')}_tmax_ntask.png",
    bbox_inches="tight",
)